## ORDINAL ENCODING


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/Mohd Rizwan/Downloads/Da Project/ML/Encoding/customer.csv")

In [3]:
df.head(2)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No

In [4]:
df.iloc[:,2:].head(2)

review education purchased
0  Average    School        No
1     Poor        UG        No

In [5]:
df.iloc[:,-1:].head(3)

purchased
0        No
1        No
2        No

In [6]:
df.iloc[:, 0:2].head(2)

age  gender
0   30  Female
1   68  Female

## Train_Test_Split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,2:-1], df.iloc[:, -1:],test_size = 0.2)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder(categories= [['Good', 'Average', 'Poor'],['School', "UG", 'PG']])

In [11]:
x_train.head(3)

review education
39     Poor        PG
4   Average        UG
34  Average    School

In [12]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Good', 'Average', 'Poor'], ['School', 'UG', 'PG']])

In [13]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [14]:
x_train[:3]


array([[2., 2.],
       [1., 1.],
       [1., 0.]])

In [15]:
x_test[:3]

array([[0., 0.],
       [1., 1.],
       [0., 2.]])

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

c:\Users\Mohd Rizwan\Python\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [19]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

c:\Users\Mohd Rizwan\Python\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Mohd Rizwan\Python\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [21]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1])