## ORDINAL ENCODING


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("customer.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'customer.csv'

In [ ]:
df.head(2)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No

In [ ]:
df.iloc[:,2:].head(2)

review education purchased
0  Average    School        No
1     Poor        UG        No

In [ ]:
df.iloc[:,-1:].head(3)

purchased
0        No
1        No
2        No

In [ ]:
df.iloc[:, 0:2].head(2)

age  gender
0   30  Female
1   68  Female

## Train_Test_Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,2:-1], df.iloc[:, -1:],test_size = 0.2)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories= [['Good', 'Average', 'Poor'],['School', "UG", 'PG']])

In [ ]:
x_train.head(3)

review education
33   Good        PG
48   Good        UG
11   Good        UG

In [ ]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Good', 'Average', 'Poor'], ['School', 'UG', 'PG']])

In [ ]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [ ]:
x_train[:3]


array([[0., 2.],
       [0., 1.],
       [0., 1.]])

In [ ]:
x_test[:3]

array([[1., 0.],
       [2., 0.],
       [2., 1.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

C:\Users\Mohd Rizwan\Python\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

C:\Users\Mohd Rizwan\Python\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\Mohd Rizwan\Python\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [ ]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0])